### ISSUE TITLE
CondaEnvironmentNotFound Error

### ISSUE THREAD

**Issue by bookamp** [enigmampc/catalyst-docs#7]
Following the instructions for Windows10:
https://github.com/enigmampc/catalyst-docs/wiki/Catalyst-Installation-Instructions-for-Windows-10-Users

and getting the following error:

CondaEnvironmentNotFoundError: Could not find environment: catalyst .
You can list all discoverable environments with `conda info --envs`.

I then tried running  running conda env create -f python2.7-environment.yml
but that generates a different error:

ResolvePackageNotFound:
  - openssl 1.0.2l 0

**Comment by abnera** [comment]
I can look into the first issue. With respect to the second error ResolvePackageNotFound, I can offer you a quick solution. Open the file `python2.7-environment.yml` and comment the line open 1.0.2l 0 you can comment it by putting the `#` in front of that line.

Example: `# openssl 1.0.2l 0`.

Do this with any of the packages that give you this error until you able to install it. 

The first error is most likely because you were not able to successfully install it with conda create. So there is no environment yet.

Try using this installation tutorial, which provides other alternatives to install:

https://github.com/enigmampc/catalyst-docs/wiki/Catalyst-Installation-For-Linux,-MacOS,-and-Windows-platforms-(Conda)

**Comment by lacabra** [comment]
@bookamp Please refer to the updated installation instructions available at https://enigmampc.github.io/catalyst/install.html
I have also updated `etc/python2.7-environment.yml` through troubleshooting various installations with different users, so you may want to download it again from https://github.com/enigmampc/catalyst/blob/master/etc/python2.7-environment.yml and try the installation again. In addition to the written instructions on the link above, we have also posted some videos in case that is of help: 
https://enigmampc.github.io/catalyst/videos.html

Join us on our Discord group where we can further assist you with your install:
https://discord.gg/SJK32GY
